routes/web.php
<?php

use App\Category;
use Illuminate\Support\Facades\Route;


//Web Page Rutes
Route::get('/','HomeController@index')->name('home');

//prebaruvajne na postoj po kategorija
Route::get('/category/{slug}','PostController@postByCategory')->name('category.posts');
//prebaruvajne na postoj po tag
Route::get('/tag/{slug}','PostController@postByTag')->name('tag.posts');

Route::get('/post/{slug}','PostController@details')->name('post.details');
Route::get('/posts','PostController@index')->name('post.index');

Route::post('subscriber','SubscriberController@store')->name('subscriber.store');
Route::get('/search','SearchController@search')->name('search');

//probaruvajne po avtor
Route::get('profile/{username}','AuthorController@profile')->name('author.profile');


Auth::routes();
Route::group(['middleware' =>['auth']], function()
{
    Route::post('/favorite/{post}/add','FavoriteController@add')->name('post.favorite');
    Route::post('/comment/{post}','CommentController@store')->name('comment.store');
});


//admin routes
Route::group(['as' => 'admin.','prefix' => 'admin','namespace' => 'Admin','middleware' =>['auth','admin']], function()
{
    Route::get('/dashboard','DashboardController@index')->name('dashboard');

    Route::get('/settings','SettingsController@index')->name('settings');
    Route::put('/profile-update','SettingsController@updateProfile')->name('profile.update');
    Route::put('/password-update','SettingsController@updatePassword')->name('password.update');


    Route::resource('/tag','TagController');
    Route::resource('/category','CategoryController');
    Route::resource('/post','PostController');

    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('/comments','CommentController@index')->name('comments.index');
    Route::delete('/comments/{id}','CommentController@destroy')->name('comments.destroy');

    Route::get('/authors','AuthorController@index')->name('authors.index');
    Route::delete('/authors/{id}','AuthorController@destroy')->name('authors.destroy');

    Route::get('/pending/post','PostController@pending')->name('post.pending');
    Route::get('/post/{id}/approve','PostController@approve')->name('post.approve');

    Route::get('/subscriber','SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{subscriber}','SubscriberController@destroy')->name('subscriber.destroy');

});

//author routes
Route::group(['as' => 'author.','prefix' => 'author','namespace' => 'Author','middleware' =>['auth','author']], function()
{
    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    Route::resource('/post','PostController');

    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('/comments','CommentController@index')->name('comments.index');
    Route::delete('/comments/{id}','CommentController@destroy')->name('comments.destroy');

    Route::get('/settings','SettingsController@index')->name('settings');
    Route::put('/profile-update','SettingsController@updateProfile')->name('profile.update');
    Route::put('/password-update','SettingsController@updatePassword')->name('password.update');
});

app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;

class AuthorController extends Controller
{
    public function index(){
       $authors=User::authors()
            ->withCount('posts')
            ->withCount('comments')
            ->withCount('favorite_posts')
            ->get();

       return view('admin.authors',compact('authors'));
    }

    public function destroy($id)
    {
        $author=User::findOrFail($id)->delete();

        Toastr::success('Author Deleted','Success');

        return redirect()->back();

    }
}

resources/views/admin/authors.blade.php
@extends('layouts.backend.app')

@section('title',"Category")

@push('css')

    <link href="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}"
          rel="stylesheet">
@endpush

@section('content')
    <div class="container-fluid">
        <!-- Exportable Table -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                           All Authors
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"
                                   role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Posts</th>
                                    <th>Comments</th>
                                    <th>Favorite Posts</th>
                                    <th>Created At:</th>
                                    <th>Actions:</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Posts</th>
                                    <th>Comments</th>
                                    <th>Favorite Posts</th>
                                    <th>Created At:</th>
                                    <th>Actions:</th>
                                </tr>
                                </tfoot>
                                <tbody>

                                @foreach($authors as $key=>$author)
                                    <tr>
                                        <td>{{$key + 1 }}</td>
                                        <td>{{$author->name }}</td>
                                        <td>{{$author->posts_count }}</td>
                                        <td>{{$author->comments_count }}</td>
                                        <td>{{$author->favorite_posts_count }}</td>
                                        <td>{{$author->created_at }}</td>
                                        <td class="text-center">

                                            <button class="btn btn-danger waves-effect" type="button"
                                                    onclick="deleteAuthors({{$author->id}})">
                                                <i class="material-icons">delete</i>
                                            </button>
                                            <form id="delete-form-{{$author->id}}"
                                                  action="{{route('admin.authors.destroy',$author->id)}}" method="Post"
                                                  style="display: none">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </td>

                                    </tr>
                                @endforeach


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Exportable Table -->
    @endsection

    @push('js')
        <!-- Jquery DataTable Plugin Js -->
            <script src="{{asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
            <script
                src="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
            <script
                src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
            <script
                src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
            <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
            <script
                src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
            <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
            <script
                src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
            <script
                src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>

            <script src="{{asset('assets/backend/js/pages/tables/jquery-datatable.js')}}"></script>
            <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.5.1/dist/sweetalert2.all.min.js"></script>
            {{--Za deletirajne na tag--}}
            <script>
                function deleteAuthors(id) {
                    const swalWithBootstrapButtons = Swal.mixin({
                        customClass: {
                            confirmButton: 'btn btn-success',
                            cancelButton: 'btn btn-danger'
                        },
                        buttonsStyling: false
                    })

                    swalWithBootstrapButtons.fire({
                        title: 'Are you sure?',
                        text: "You won't be able to revert this!",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonText: 'Yes, delete it!',
                        cancelButtonText: 'No, cancel!',
                        reverseButtons: true
                    }).then((result) => {
                        if (result.value) {
                            event.preventDefault();
                            document.getElementById('delete-form-' + id).submit();
                        } else if (
                            /* Read more about handling dismissals below */
                            result.dismiss === Swal.DismissReason.cancel
                        ) {
                            swalWithBootstrapButtons.fire(
                                'Cancelled',
                                'Your imaginary file is safe :)',
                                'error'
                            )
                        }
                    })
                }
            </script>
    @endpush

resources/views/admin/settings.blade.php
@extends('layouts.backend.app')

@section('title',"Settings")

@push('')

@endpush


@section('content')
    <div class="container-fluid">
        <!-- Tabs With Icon Title -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            SETTINGS
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active">
                                <a href="#profile_with_icon_title" data-toggle="tab">
                                    <i class="material-icons">face</i> Update
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#change_password" data-toggle="tab">
                                    <i class="material-icons">change_history</i> Password
                                </a>
                            </li>
                        </ul>

                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane fade in active" id="profile_with_icon_title">
                                <!-- Horizontal Layout -->
                                <div class="row clearfix">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <div class="card">
                                            <div class="body">
                                                <form class="form-horizontal" action="{{route('admin.profile.update')}}" method="POST" enctype="multipart/form-data">
                                                    @csrf
                                                    @method('PUT')
                                                    <div class="row clearfix">
                                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                            <label for="name">Name:</label>
                                                        </div>
                                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                            <div class="form-group">
                                                                <div class="form-line">
                                                                    <input type="text" id="name" class="form-control" placeholder="Enter your name" name="name" value="{{Auth::user()->name}}">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="row clearfix">
                                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                            <label for="email">Email Address</label>
                                                        </div>
                                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                            <div class="form-group">
                                                                <div class="form-line">
                                                                    <input type="text" id="email" class="form-control" placeholder="Enter your email address" name="email" value="{{Auth::user()->email}}">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="row clearfix">
                                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                            <label for="image">Profile Image</label>
                                                        </div>
                                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                            <div class="form-group">
                                                                <div class="form-line">
                                                                    <input type="file" name="image">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="row clearfix">
                                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                            <label for="about">About</label>
                                                        </div>
                                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                            <div class="form-group">
                                                                <div class="form-line">
                                                                    <textarea row="5"
                                                                        type="about" id="about" class="form-control" placeholder="Enter your email address" name="about">
                                                                        {{Auth::user()->about}}
                                                                    </textarea>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>


                                                    <div class="row clearfix">
                                                        <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Update</button>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- #END# Horizontal Layout -->
                            </div>
                            <div role="tabpanel" class="tab-pane fade" id="change_password">
                                <div class="row clearfix">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <div class="card">
                                            <div class="body">
                                                <form class="form-horizontal" action="{{route('admin.password.update')}}" method="POST" enctype="multipart/form-data">
                                                    @csrf
                                                    @method('PUT')
                                                    <div class="row clearfix">
                                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                            <label for="old_password">Old Password : </label>
                                                        </div>
                                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                            <div class="form-group">
                                                                <div class="form-line">
                                                                    <input type="password" id="old_password" class="form-control" placeholder="Enter your old password" name="old_password">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="row clearfix">
                                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                            <label for="password">New Password : </label>
                                                        </div>
                                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                            <div class="form-group">
                                                                <div class="form-line">
                                                                    <input type="password" id="password" class="form-control" placeholder="Enter your new password" name="password">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="row clearfix">
                                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                            <label for="confirm_password">Confirm Password : </label>
                                                        </div>
                                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                            <div class="form-group">
                                                                <div class="form-line">
                                                                    <input type="password" id="confirm_password" class="form-control" placeholder="Enter your new password again" name="password_confirmation">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="row clearfix">
                                                        <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Update</button>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- #END# Horizontal Layout -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Tabs With Icon Title -->
    </div>
@endsection

@push('')

@endpush