routes/web.php
<?php

use App\Category;
use Illuminate\Support\Facades\Route;


//Web Page Rutes
Route::get('/','HomeController@index')->name('home');

//prebaruvajne na postoj po kategorija
Route::get('/category/{slug}','PostController@postByCategory')->name('category.posts');
//prebaruvajne na postoj po tag
Route::get('/tag/{slug}','PostController@postByTag')->name('tag.posts');

Route::get('/post/{slug}','PostController@details')->name('post.details');
Route::get('/posts','PostController@index')->name('post.index');

Route::post('subscriber','SubscriberController@store')->name('subscriber.store');
Route::get('/search','SearchController@search')->name('search');

//probaruvajne po avtor
Route::get('profile/{username}','AuthorController@profile')->name('author.profile');


Auth::routes();
Route::group(['middleware' =>['auth']], function()
{
    Route::post('/favorite/{post}/add','FavoriteController@add')->name('post.favorite');
    Route::post('/comment/{post}','CommentController@store')->name('comment.store');
});


//admin routes
Route::group(['as' => 'admin.','prefix' => 'admin','namespace' => 'Admin','middleware' =>['auth','admin']], function()
{
    Route::get('/dashboard','DashboardController@index')->name('dashboard');

    Route::get('/settings','SettingsController@index')->name('settings');
    Route::put('/profile-update','SettingsController@updateProfile')->name('profile.update');
    Route::put('/password-update','SettingsController@updatePassword')->name('password.update');


    Route::resource('/tag','TagController');
    Route::resource('/category','CategoryController');
    Route::resource('/post','PostController');

    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('/comments','CommentController@index')->name('comments.index');
    Route::delete('/comments/{id}','CommentController@destroy')->name('comments.destroy');

    Route::get('/authors','AuthorController@index')->name('authors.index');
    Route::delete('/authors/{id}','AuthorController@destroy')->name('authors.destroy');

    Route::get('/pending/post','PostController@pending')->name('post.pending');
    Route::get('/post/{id}/approve','PostController@approve')->name('post.approve');

    Route::get('/subscriber','SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{subscriber}','SubscriberController@destroy')->name('subscriber.destroy');

});

//author routes
Route::group(['as' => 'author.','prefix' => 'author','namespace' => 'Author','middleware' =>['auth','author']], function()
{
    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    Route::resource('/post','PostController');

    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('/comments','CommentController@index')->name('comments.index');
    Route::delete('/comments/{id}','CommentController@destroy')->name('comments.destroy');

    Route::get('/settings','SettingsController@index')->name('settings');
    Route::put('/profile-update','SettingsController@updateProfile')->name('profile.update');
    Route::put('/password-update','SettingsController@updatePassword')->name('password.update');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public function posts(){
        return $this->belongsToMany(Post::class)->withTimestamps();
    }
}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Tag;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use Str;

class TagController extends Controller
{

    public function index()
    {
        $tags=Tag::latest()->get();
        return view('admin.tag.index',compact('tags'));
    }


    public function create()
    {
        return view('admin.tag.create');
    }


    public function store(Request $request)
    {
       $this->validate($request,[

           'name'=>'required',
       ]);

       $tag=new Tag();

       $tag->name=$request->name;
       $tag->slug=Str::slug($request->name);
       $tag->save();
       Toastr::success('Tag saved','Success');
       return redirect()->route('admin.tag.index');
    }


    public function edit($id)
    {
        $tag=Tag::findorfail($id);

        return view('admin.tag.edit',compact('tag'));
    }


    public function update(Request $request, $id)
    {
        $this->validate($request,[

            'name'=>'required',
        ]);

        $tag=Tag::find($id);

        $tag->name=$request->name;
        $tag->slug=Str::slug($request->name);
        Toastr::success('Tag Updated','Success');
        $tag->save();
        return redirect()->route('admin.tag.index');
    }

    public function destroy($id)
    {
        Tag::find($id)->delete();

        Toastr::success('Tag deleted','Success');

        return redirect()->back();
    }
}

resources/views/admin/tag/create.blade.php
@extends('layouts.backend.app')

@section('title',"Dashboard")

@push('css')

@endpush

@section('content')


<div class="container-fluid">

    <!-- Vertical Layout -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Add New Tag
                    </h2>
            {{--        <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>--}}
                </div>
                <div class="body">
                    <form action="{{route('admin.tag.store')}}" method="Post">
                        @csrf
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="name" class="form-control" name="name" placeholder="">
                                <label class="form-label">Tag Name</label>
                            </div>
                        </div>

                        <a class="btn btn-danger m-t-15 waves-effect"
                           href="{{route('admin.tag.index')}}">
                            Back
                        </a>

                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
    <!-- #END# Vertical Layout -->
    <!-- Vertical Layout | With Floating Label -->
@endsection
@push('js')

@endpush

resources/views/admin/tag/edit.blade.php
@extends('layouts.backend.app')

@section('title',"Dashboard")

@push('css')

@endpush

@section('content')


<div class="container-fluid">

    <!-- Vertical Layout -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Edit Tag
                    </h2>
                </div>
                <div class="body">
                    <form action="{{route('admin.tag.update',$tag->id)}}" method="Post">
                        @csrf
                        @method('PUT')
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="name" class="form-control" name="name" value="{{$tag->name}}" placeholder="">
                                <label class="form-label">Tag Name</label>
                            </div>
                        </div>

                        <a class="btn btn-danger m-t-15 waves-effect"
                           href="{{route('admin.tag.index')}}">
                            Back
                        </a>

                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
    <!-- #END# Vertical Layout -->
    <!-- Vertical Layout | With Floating Label -->
@endsection
@push('js')

@endpush

resources/views/admin/tag/index.blade.php
@extends('layouts.backend.app')

@section('title',"Tag")

@push('css')

    <link href="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}"
          rel="stylesheet">
@endpush

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <a href="{{route('admin.tag.create')}}" class="btn btn-primary waves-effect">

                <i class="material-icons">add</i>
                <span>Add New Tag</span>

            </a>
        </div>

        <!-- Exportable Table -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            All Tags
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"
                                   role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Post Count</th>
                                    <th>Created At:</th>
                                    <th>Updated At:</th>
                                    <th>Actions:</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Post Count</th>
                                    <th>Created At:</th>
                                    <th>Updated At:</th>
                                    <th>Actions:</th>
                                </tr>
                                </tfoot>
                                <tbody>

                                @foreach($tags as $key=>$tag)
                                    <tr>
                                        <td>{{$key + 1 }}</td>
                                        <td>{{$tag->name }}</td>
                                        <td>{{$tag->posts->count() }}</td>
                                        <td>{{$tag->created_at }}</td>
                                        <td>{{$tag->updated_at }}</td>
                                        <td class="text-center">
                                            <a href="{{route('admin.tag.edit',$tag->id)}}"
                                               class="btn btn-info waves-effect">
                                                <i class="material-icons">edit</i>
                                            </a>

                                            <button class="btn btn-danger waves-effect" type="button"
                                                    onclick="deleteTag({{$tag->id}})">
                                                <i class="material-icons">delete</i>
                                            </button>
                                            <form id="delete-form-{{$tag->id}}"
                                                  action="{{route('admin.tag.destroy',$tag->id)}}" method="Post"
                                                  style="display: none">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </td>

                                    </tr>
                                @endforeach


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Exportable Table -->
    @endsection

    @push('js')
        <!-- Jquery DataTable Plugin Js -->
            <script src="{{asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
            <script
                src="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
            <script
                src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
            <script
                src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
            <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
            <script
                src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
            <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
            <script
                src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
            <script
                src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>

            <script src="{{asset('assets/backend/js/pages/tables/jquery-datatable.js')}}"></script>
            <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.5.1/dist/sweetalert2.all.min.js"></script>
            {{--Za deletirajne na tag--}}
            <script>
                function deleteTag(id) {
                    const swalWithBootstrapButtons = Swal.mixin({
                        customClass: {
                            confirmButton: 'btn btn-success',
                            cancelButton: 'btn btn-danger'
                        },
                        buttonsStyling: false
                    })

                    swalWithBootstrapButtons.fire({
                        title: 'Are you sure?',
                        text: "You won't be able to revert this!",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonText: 'Yes, delete it!',
                        cancelButtonText: 'No, cancel!',
                        reverseButtons: true
                    }).then((result) => {
                        if (result.value) {
                            event.preventDefault();
                            document.getElementById('delete-form-' + id).submit();
                        } else if (
                            /* Read more about handling dismissals below */
                            result.dismiss === Swal.DismissReason.cancel
                        ) {
                            swalWithBootstrapButtons.fire(
                                'Cancelled',
                                'Your imaginary file is safe :)',
                                'error'
                            )
                        }
                    })
                }
            </script>
    @endpush