routes/web.php
<?php

use App\Category;
use Illuminate\Support\Facades\Route;


//Web Page Rutes
Route::get('/','HomeController@index')->name('home');

//prebaruvajne na postoj po kategorija
Route::get('/category/{slug}','PostController@postByCategory')->name('category.posts');
//prebaruvajne na postoj po tag
Route::get('/tag/{slug}','PostController@postByTag')->name('tag.posts');

Route::get('/post/{slug}','PostController@details')->name('post.details');
Route::get('/posts','PostController@index')->name('post.index');

Route::post('subscriber','SubscriberController@store')->name('subscriber.store');
Route::get('/search','SearchController@search')->name('search');

//probaruvajne po avtor
Route::get('profile/{username}','AuthorController@profile')->name('author.profile');


Auth::routes();
Route::group(['middleware' =>['auth']], function()
{
    Route::post('/favorite/{post}/add','FavoriteController@add')->name('post.favorite');
    Route::post('/comment/{post}','CommentController@store')->name('comment.store');
});


//admin routes
Route::group(['as' => 'admin.','prefix' => 'admin','namespace' => 'Admin','middleware' =>['auth','admin']], function()
{
    Route::get('/dashboard','DashboardController@index')->name('dashboard');

    Route::get('/settings','SettingsController@index')->name('settings');
    Route::put('/profile-update','SettingsController@updateProfile')->name('profile.update');
    Route::put('/password-update','SettingsController@updatePassword')->name('password.update');


    Route::resource('/tag','TagController');
    Route::resource('/category','CategoryController');
    Route::resource('/post','PostController');

    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('/comments','CommentController@index')->name('comments.index');
    Route::delete('/comments/{id}','CommentController@destroy')->name('comments.destroy');

    Route::get('/authors','AuthorController@index')->name('authors.index');
    Route::delete('/authors/{id}','AuthorController@destroy')->name('authors.destroy');

    Route::get('/pending/post','PostController@pending')->name('post.pending');
    Route::get('/post/{id}/approve','PostController@approve')->name('post.approve');

    Route::get('/subscriber','SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{subscriber}','SubscriberController@destroy')->name('subscriber.destroy');

});

//author routes
Route::group(['as' => 'author.','prefix' => 'author','namespace' => 'Author','middleware' =>['auth','author']], function()
{
    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    Route::resource('/post','PostController');

    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('/comments','CommentController@index')->name('comments.index');
    Route::delete('/comments/{id}','CommentController@destroy')->name('comments.destroy');

    Route::get('/settings','SettingsController@index')->name('settings');
    Route::put('/profile-update','SettingsController@updateProfile')->name('profile.update');
    Route::put('/password-update','SettingsController@updatePassword')->name('password.update');
});

app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;

class AuthorController extends Controller
{
    public function index(){
       $authors=User::authors()
            ->withCount('posts')
            ->withCount('comments')
            ->withCount('favorite_posts')
            ->get();

       return view('admin.authors',compact('authors'));
    }

    public function destroy($id)
    {
        $author=User::findOrFail($id)->delete();

        Toastr::success('Author Deleted','Success');

        return redirect()->back();

    }
}

app/Http/Controllers/Author/CommentController.php
<?php

namespace App\Http\Controllers\Author;

use App\Comment;
use App\Http\Controllers\Controller;
use Auth;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    public function index(){
        $posts=Auth::user()->posts;

        return view('author.comments',compact('posts'));
    }

    public function destroy($id){
        $commnets=Comment::findorfail($id)->delete();

        if($commnets->post->user->id == Auth::id())
        {
            Toastr::success('Comment sacesfully deleted','Success');
            return redirect()->back();
        }
        else {
            Toastr::error('You have no autority to delete this comment','Error');
            return redirect()->back();
        }
    }
}

app/Http/Controllers/Author/DashboardController.php
<?php

namespace App\Http\Controllers\Author;

use App\Http\Controllers\Controller;
use Auth;
use Illuminate\Http\Request;

class DashboardController extends Controller
{

    public function index()
    {
        $user = Auth::user();

        $posts = $user->posts();

        $popular_posts = $user->posts()
            ->withCount('comments')
            ->withCount('favorite_to_users')
            ->orderBy('view_count', 'desc')
            ->orderBy('comments_count')
            ->orderBy('favorite_to_users_count')
            ->take(5)->get();

        $total_pending_posts=$posts->where('is_approved',false)->count();

        $all_views=Auth::user()->posts()->sum('view_count');

        return view('author.dashboard',compact(
            'posts',
            'popular_posts',
            'total_pending_posts',
            'all_views'
        ));
    }

}

app/Http/Controllers/Author/FavoriteController.php
<?php

namespace App\Http\Controllers\Author;

use App\Http\Controllers\Controller;
use Auth;
use Illuminate\Http\Request;

class FavoriteController extends Controller
{
    public function index()
    {
        $posts=Auth::user()->favorite_posts;

        return view('author.favorite',compact('posts'));
    }
}

app/Http/Controllers/Author/PostController.php
<?php

namespace App\Http\Controllers\Author;

use App\Category;
use App\Http\Controllers\Controller;
use App\Notifications\NewAuthorPost;
use App\Post;
use App\Tag;
use App\User;
use Brian2694\Toastr\Facades\Toastr;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use Str;

class PostController extends Controller
{

    public function index()
    {
        $posts=Auth::user()->posts()->latest()->get();

        return view('author.post.index',compact('posts'));
    }


    public function create()
    {
        $categories=Category::all();
        $tags=Tag::all();
        return view('author.post.create',compact('categories','tags'));
    }


    public function store(Request $request)
    {
        $this->validate($request,[
            'title'=>'required',
            'image'=>'required',
            'categories'=>'required',
            'tags'=>'required',
            'body'=>'required',
        ]);

        $image=$request->file('image');

        $slug=Str::slug($request->title);

        if(isset($image)){
            $currentDate = Carbon::now()->toDateString();
            $imageName = $slug . '-' . $currentDate . '-' . uniqid() . '.' . $image->getClientOriginalExtension();

            if (!Storage::disk('public')->exists('post')) {//ako ne postoj kreiraj novo
                Storage::disk('public')->makeDirectory('post');//kreiraj novo
            }
                $postImage = Image::make($image)->resize(1600, 1066)->stream();
                Storage::disk('public')->put('post/' . $imageName, $postImage);

        }
        else{
            $imageName='default.png';
        }

        $post=new Post();

        $post->user_id=Auth()->id();
        $post->title=$request->title;
        $post->slug=$slug;
        $post->image=$imageName;
        $post->body=$request->body;

        if(isset($request->status)){
            $post->status=true;
        }else{
            $post->status=false;
        }
        $post->is_approved=false;
        $post->save();

        $post->categories()->attach($request->categories);
        $post->tags()->attach($request->tags);

        $users=User::where('role_id','1')->get();

        Notification::send($users,new NewAuthorPost($post));


        Toastr::success('Post Created','Success');
        return redirect()->route('author.post.index');

    }

    public function show(Post $post)
    {
        if(!$post->user_id  = Auth::id())
        {
            Toastr::error('You have no autorization to access this post','error');
            return redirect()->back();
        }

        return view('author.post.show',compact('post'));
    }


    public function edit(Post $post)
    {
        if(!$post->user_id  = Auth::id())
        {
            Toastr::error('You have no autorization to access this post','error');
            return redirect()->back();
        }
        $categories=Category::all();
        $tags=Tag::all();
        return view('author.post.edit',compact('categories','tags','post'));
    }


    public function update(Request $request, Post $post)
    {
        if(!$post->user_id  = Auth::id())
        {
            Toastr::error('You have no autorization to access this post','error');
            return redirect()->back();
        }
        $this->validate($request,[
            'title'=>'required',
            'categories'=>'required',
            'tags'=>'required',
            'body'=>'required',
        ]);

        $image=$request->file('image');

        $slug=Str::slug($request->title);

        if(isset($image)){
            $currentDate = Carbon::now()->toDateString();
            $imageName = $slug . '-' . $currentDate . '-' . uniqid() . '.' . $image->getClientOriginalExtension();

            if (!Storage::disk('public')->exists('post')) {//ako ne postoj kreiraj novo
                Storage::disk('public')->makeDirectory('post');//kreiraj novo
            }
            //delete old image
            if(Storage::disk('public')->exists('post/'.$post->image)) {
                (Storage::disk('public')->delete('post/' . $post->image));

            }

            $postImage = Image::make($image)->resize(1600, 1066)->stream();
            Storage::disk('public')->put('post/' . $imageName, $postImage);

        }
        else{
            $imageName=$post->image;
        }

        $post->user_id=Auth()->id();
        $post->title=$request->title;
        $post->slug=$slug;
        $post->image=$imageName;
        $post->body=$request->body;

        if(isset($request->status)){
            $post->status=true;
        }else{
            $post->status=false;
        }
        $post->is_approved=false;
        $post->save();

        $post->categories()->sync($request->categories);
        $post->tags()->sync($request->tags);
        Toastr::success('Post Updated','Success');
        return redirect()->route('author.post.index');
    }


    public function destroy(Post $post)
    {
        if(Storage::disk('public')->exists('post/'.$post->image))
        {
            Storage::disk('public')->delete('post/'.$post->image);
        }
        $post->categories()->detach();
        $post->tags()->detach();

        $post->delete();
        Toastr::success('Post Deleted','Success');

        return redirect()->route('author.post.index');
    }
}

app/Http/Controllers/Author/SettingsController.php
<?php

namespace App\Http\Controllers\Author;

use App\Http\Controllers\Controller;
use App\User;
use Auth;
use Brian2694\Toastr\Facades\Toastr;
use Carbon\Carbon;
use Hash;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use Str;

class SettingsController extends Controller
{
    public function index(){
        return view('author.settings');
    }

    public function updateProfile(Request $request){
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required',
            'image' => 'required',
        ]);

        $image=$request->file('image');
        $slug = Str::slug($request->name);

        $user=User::findorfail(Auth::id());

        if (isset($image)) {
            $currentDate = Carbon::now()->toDateString();
            $imageName = $slug . '-' . $currentDate . '-' . uniqid() . '.' . $image->getClientOriginalExtension();

            if (!Storage::disk('public')->exists('profile')) {//ako ne postoj kreiraj novo
                Storage::disk('public')->makeDirectory('profile');//kreiraj novo
            }
            //delete old image
            if (Storage::disk('public')->exists('profile/' . $user->image)) {
                (Storage::disk('public')->delete('profile/' . $user->image));
            }

            $profile = Image::make($image)->resize(500, 500)->stream();
            Storage::disk('public')->put('profile/' . $imageName, $profile);

        } else {
            $imageName = $user->image;
        }

        $user->name=$request->name;
        $user->email=$request->email;
        $user->image=$imageName;
        $user->about=$request->about;

        $user->save();

        Toastr::success('User Updated', 'Success');
        return redirect()->back();

    }

    public function updatePassword(Request $request){
        $this->validate($request, [
            'old_password' => 'required',
            'password' => 'required|confirmed',
        ]);

        $hashPassword=Auth::user()->password;

        if(Hash::check($request->old_password,$hashPassword)){
            if(!Hash::check($request->password,$hashPassword)){
                $user=User::find(Auth::id());
                $user->password=Hash::make($request->password);
                $user->save();
                Toastr::success('Password changed', 'Success');
                Auth::logout();
                return redirect()->back();
            }
            else{
                Toastr::error('Password cannot be the same as the old one', 'Error');
                return redirect()->back();
            }
        }else{
            Toastr::error('Passwords must match', 'Error');
            return redirect()->back();
        }
    }
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class AuthorController extends Controller
{
    public function profile($username){
       $author=User::where('username',$username)->first();
       $posts=$author->posts()->approved()->published()->get();

       return view('profile',compact('author','posts'));
    }
}

resources/views/author/settings.blade.php
@extends('layouts.backend.app')

@section('title',"Settings")

@push('')

@endpush


@section('content')
    <div class="container-fluid">
        <!-- Tabs With Icon Title -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            SETTINGS
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active">
                                <a href="#profile_with_icon_title" data-toggle="tab">
                                    <i class="material-icons">face</i> Update
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#change_password" data-toggle="tab">
                                    <i class="material-icons">change_history</i> Password
                                </a>
                            </li>
                        </ul>

                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane fade in active" id="profile_with_icon_title">
                                <!-- Horizontal Layout -->
                                <div class="row clearfix">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <div class="card">
                                            <div class="body">
                                                <form class="form-horizontal" action="{{route('author.profile.update')}}" method="POST" enctype="multipart/form-data">
                                                    @csrf
                                                    @method('PUT')
                                                    <div class="row clearfix">
                                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                            <label for="name">Name:</label>
                                                        </div>
                                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                            <div class="form-group">
                                                                <div class="form-line">
                                                                    <input type="text" id="name" class="form-control" placeholder="Enter your name" name="name" value="{{Auth::user()->name}}">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="row clearfix">
                                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                            <label for="email">Email Address</label>
                                                        </div>
                                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                            <div class="form-group">
                                                                <div class="form-line">
                                                                    <input type="text" id="email" class="form-control" placeholder="Enter your email address" name="email" value="{{Auth::user()->email}}">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="row clearfix">
                                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                            <label for="image">Profile Image</label>
                                                        </div>
                                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                            <div class="form-group">
                                                                <div class="form-line">
                                                                    <input type="file" name="image">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="row clearfix">
                                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                            <label for="about">About</label>
                                                        </div>
                                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                            <div class="form-group">
                                                                <div class="form-line">
                                                                    <textarea row="5"
                                                                        type="about" id="about" class="form-control" placeholder="Enter your email address" name="about">
                                                                        {{Auth::user()->about}}
                                                                    </textarea>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>


                                                    <div class="row clearfix">
                                                        <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Update</button>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- #END# Horizontal Layout -->
                            </div>
                            <div role="tabpanel" class="tab-pane fade" id="change_password">
                                <div class="row clearfix">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <div class="card">
                                            <div class="body">
                                                <form class="form-horizontal" action="{{route('author.password.update')}}" method="POST" enctype="multipart/form-data">
                                                    @csrf
                                                    @method('PUT')
                                                    <div class="row clearfix">
                                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                            <label for="old_password">Old Password : </label>
                                                        </div>
                                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                            <div class="form-group">
                                                                <div class="form-line">
                                                                    <input type="password" id="old_password" class="form-control" placeholder="Enter your old password" name="old_password">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="row clearfix">
                                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                            <label for="password">New Password : </label>
                                                        </div>
                                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                            <div class="form-group">
                                                                <div class="form-line">
                                                                    <input type="password" id="password" class="form-control" placeholder="Enter your new password" name="password">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="row clearfix">
                                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                            <label for="confirm_password">Confirm Password : </label>
                                                        </div>
                                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                            <div class="form-group">
                                                                <div class="form-line">
                                                                    <input type="password" id="confirm_password" class="form-control" placeholder="Enter your new password again" name="password_confirmation">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="row clearfix">
                                                        <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Update</button>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- #END# Horizontal Layout -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Tabs With Icon Title -->
    </div>
@endsection

@push('')

@endpush